### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by hzoo** [boennemann/alle#1]
Oops I accidentally clicked this too early.. no thoughts yet 😝
### linking packages is a separate step (that takes time)

Yeah it's unfortunate that [bootstrap](https://github.com/lerna/lerna#bootstrap) is a step currently.

Bootstrap is definetely slow but shouldn't be after the initial one though I thought since you'll run it again after adding a dep? Yeah adding/removing deps with that shouldn't require a lot of work.

All the current ideas related are related to doing linking differently (https://github.com/lerna/lerna/issues/11#issuecomment-234738279). I wasn't even thinking about a way to not have to do it so that's interesting to bring up 😄! Putting it in `node_modules/` seems like a hack too which I never thought of doing but sounds interesting.
### links are a hack module.exports = require('./path/to/the-actual-thing')

Yeah linking as mentioned above it's a hack that was working for babel and only works in certain situations (doesn't currently support binary https://github.com/lerna/lerna/pull/192, currently one top level entry file, no nested folders https://github.com/lerna/lerna/issues/11).

And maybe the linking part would be better as an actual lerna issue actually?
### incompatibility with Greenkeeper

So I was already thinking of moving all devDeps up to the top level in Babel actually given the top level node_modules (every [package](https://github.com/babel/babel#packages) is importing [babel-helper-plugin-test-runner](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-export-extensions/package.json#L16)).

I wasn't sure about dependencies though? Yeah I guess you could find all requires/imports and add them to the top level and then and publish time you write them into deps - worth trying out.
### maintaining dependencies that more than one package depends on (see also 5)

Babel uses `^` everywhere so we don't (shouldn't?) have different versions of the same dependency I would think. Or maybe we don't have many external deps other than for babel-cli and babel-core since everything else is plugins/helpers.
### duplicated metadata in package.json

Didn't really think about this since we just copy the package.json from another file so it's a convenience thing but I can see it being a pain if you have to update all of them anyway. This could just be a feature request in lerna. I guess you could make a yeoman generator when making a new package or just make that a feature that does some boilerplate as an init. We already rewrite the package.json when bootstrap so this is just doing so as a step before publishing.
## It sounds like the main issue is that bootstrap is slow and maybe not even required and that the current way of linking is brittle and doesn't support certain use cases well.

The other issues I was thinking of had to do with versioning.

https://github.com/lerna/lerna#how-it-works - fixed/independent mode. Independent mode is great but it should work with github labels (semver) or commits. More discussion in https://github.com/lerna/lerna/issues/298 and https://github.com/babel/notes/blob/master/2016-07/july-31.md#future-of-babels-release-process-and-its-ecosystem regarding having a plugin ecosystem and how we want to deal with that and breaking changes.

Ok I realize this is an aside at this point but: thought it would be interesting if something (greenkeeper) could also apply a codemod/autofix if possible when doing a pr for a breaking change to deal with api changes. Also awesome would be that as an open source maintainer you could be notified when a dependent project breaks (although it would have to check if the project was already failing due to false positives).

**Comment by boennemann** [comment]
@hzoo No worries :P Just ping me once you've updated the issue :)

**Comment by hzoo** [comment]
@boennemann Ok dono how helpful, I'l think about it again tomorrow. cc @nolanlawson

**Comment by gigabo** [comment]
> moving all devDeps up to the top level

We've moved most of ours [to the top](https://github.com/redfin/react-server/blob/master/package.json#L14) in React Server.  Works great except for package binaries (e.g. [`rimraf`](https://github.com/redfin/react-server/blob/master/packages/react-server-cli/package.json#L9)).

**Comment by hzoo** [comment]
Ok cool, we should recommend doing that in the readme then

**Comment by boennemann** [comment]
> Putting it in node_modules/ seems like a hack too which I never thought of doing but sounds interesting.

My wording wasn't the best here, so I updated the README.md to be more precise. Everything we ever do is a hack, the question is what the side effects are and how well we can handle them.
Linking modules, no matter what way, always has unwanted side-effects that break code, which isn't what we would want to deal with.

Using a folder named `node_modules` is making use of how the require algorithm is implemented. It might be confusing, because node_modules folder tend to get ignored in a git repo, and it's adding an extra folder level. However these are side effects we could live with.

> Yeah I guess you could find all requires/imports and add them to the top level

I added another paragraph that lays out a mechanism that would be easier to implement, and maybe a bit more tedious to use.

> Babel uses ^ everywhere so we don't (shouldn't?) have different versions of the same dependency I would think.

Afaik pouchdb ran into bug because of this.

> thought it would be interesting if something (greenkeeper) could also apply a codemod/autofix
> awesome would be that as an open source maintainer you could be notified when a dependent project breaks

We're planning on adding better tools for package authors to Greenkeeper :)

---

Thanks for your thoughts @hzoo!

**Comment by nolanlawson** [comment]
> Babel uses ^ everywhere so we don't (shouldn't?) 

We use exact versions because we are paranoid. 😛 Also we aren't using `version: independent` so when we publish multiple packages at the exact same version we like to link them to each other with exact versions (this is also useful for peerDeps to warn users when they have mismatched versions).

> Afaik pouchdb ran into bug because of this.

Yeah we accidentally had two versions of `js-extend`; one in one sub-package and another in another. Downside of exact versions. 😅 

I think ultimately what we will do is go with the `packages/node_modules` solution and just grep each module's source for `import` statements to build up the deps/devDeps in each sub-package at publish time. Since we're using ES6 modules instead of CJS this is actually super easy to do because we just look for that particular keyword, e.g. [using acorn like Rollup does](https://github.com/rollup/rollup/blob/78f044118991beb0785abc3de4fa5a92addeceb6/src/Module.js).

I don't want to make it seem like we're hostile to Lerna; I actually really like Lerna and feel like it pushed us in the right direction, even if we may end up dropping it. Maybe PouchDB is just a weird use case and so Lerna wasn't a good fit. I can sum up some of our difficulties, though, in case it's helpful to you @hzoo:
- `lerna run` is a bit too slow due to running multiple processes; I ended up writing one big `build-modules.js` script which worked much more nicely
- `lerna bootstrap` is fairly slow as well; been testing @boennemann's solution and it works perfectly with no bootstrap step.
- `require('./path/to/the-actual-thing')` was a big problem for us because we needed ES6 module exports in order to get the Rollup magic, so actually we're currently [relying on a fork of Lerna](https://github.com/pouchdb/pouchdb/blob/28fd4dcc350fd07a0714aeff9d9c578215c669ad/package.json#L57) containing my ES6 module version from https://github.com/lerna/lerna/pull/120 (actually even this one had a bug in Rollup that I couldn't figure out, so I had to make an even nastier fork... obviously this situation is sub-optimal because we're already a few versions behind on Lerna)

**Comment by patrickheeney** [comment]
@nolanlawson I created lerna/lerna#11 to try and figure out a better approach for lerna. Some questions about your difficulties:
- What did your `build-modules.js` do differently? Is this open source?
- Have you tried `symlinks` or any some of the PRs to add `npm link` or others?
- It looks like you modified the bootstrap command. If you had the ability to override the built in bootstrap and add your own, would this have worked for you?

**Comment by nolanlawson** [comment]
@patrickheeney My `build-modules.js` ([source](https://github.com/pouchdb/pouchdb/blob/28fd4dcc350fd07a0714aeff9d9c578215c669ad/bin/build-modules.js)) runs Rollup for all packages, and it does so using `Promise.all()` so essentially parallelizing all builds and doing them all within a single process. I found the runtime using `lerna run` with individual Rollup-based build scripts to be pretty slow in comparison (can't recall the exact numbers, but let's say 2 seconds vs 20 seconds).

Haven't tried symlinks, nope. I develop on Windows and others are on Linux/Mac, so kinda worry how it would work cross-plat. 😅 

My modifications to the bootstrap command essentially made it spit out `export * from 'path/to/package'` instead of `module.exports = ...` and added jsnext:main ([source](https://github.com/nolanlawson/lerna/blob/b195dfb3eba6148594d804abc4b75d19130bec96/src/commands/BootstrapCommand.js#L85-L91)). Also it worked around an apparent Rollup bug (https://github.com/rollup/rollup-plugin-node-resolve/issues/35). Being able to hook in and provide my own output files would have definitely helped, yes. Although the alternative `node_modules` approach avoids this issue entirely by just pointing `require`/`import` to the package itself.

**Comment by patrickheeney** [comment]
@nolanlawson I think they have some good cross-plat symlink libraries but not required with the proposed approach so will leave that discussion for elsewhere. 

---

I could have sworn I tried the node_modules approach as one of the dozen I tried in that other issue. My use case is a bit different however. I built some scripts similar to lerna to manage packages as separate repos vs a mono repo. I had many reasons not use a mono repo (unrelated client projects, unrelated libraries and components, private packages, access control). I also use the lerna mono repo for some things that do make sense (related packages).

I haven't quite solved all the pieces yet but I think this approach could also work for it. My goal was to bring any code into this environment and opt-in to the global shared boilerplate tools,  publishing tools, and some automation scripts. I hope to get some of the same conveniences as the mono repo but without having to use one. I am even toying with the idea of using both: lerna mono repo inside of this shared environment. Since `node_modules` traverses up the directory, it shouldn't matter how far you nest within `packages/`.

**Comment by hzoo** [comment]
So maybe we should just do https://github.com/lerna/lerna/issues/174 - if lerna's commands are outside of core it just becomes a nice api to read/write package.json + other built-ins/apis so you could make your own bootstrap, etc.

**Comment by patrickheeney** [comment]
@hzoo It would have to be in combination with the ideas in this repo or it would fall short. My contributions to lerna were rejected for being out of scope so if that issue becomes approved, it would give me a chance to build on top of the project rather then create a new one.

**Comment by hzoo** [comment]
@nolanlawson We don't use `lerna run` in babel either so we didn't feel the pain there given we had a set of scripts to run tests https://github.com/babel/babel/blob/master/scripts/test.sh

It's mostly bootstrap (up to date transpired project dependencies) + publish and then https://github.com/lerna/lerna-changelog atm.

All super interesting to me, I don't think we are tied to bootstrap or anything - that just happened to be what worked (i'm sure that's the case for everything in lerna (bootstrap -> single file, published with fixed versions) which was why independent mode was added as a later thing

**Comment by jimthedev** [comment]
Getting React Native's packager to work in this configuration has proved to be a bit tricky. In theory it supports adding multiple projectRoots so you could have the src code in packages/node_modules and have the react-native dependency at a higher level in the tree. In practice however, it seems RN/Xcode make a lot of assumptions about the  relative file paths in your project and you'd need to heavily modify the .xcodeproj to account for the monorepo setup. I've been unable to figure it out so far. RN did work well in Lerna since the deps were at the same level that React Native expects. 

Glad to hear this works well with rollup. As a user I'm excited to see or contribute to a few reference examples with different configurations / bundlers. I think that would help to flesh out the current limitations of this method.
